### Obtener todos los tipos

GET http://localhost:3000/api/tipos/

### Devolver una raza

GET http://localhost:3000/api/tipos/Perry


### Crear un tipo 

POST http://localhost:3000/api/tipos/
Content-Type: application/json

{
  "especie": "Perro",
  "raza": "Bolt"
}

### Actualizar un tipo
PUT http://localhost:3000/api/tipos/Perry   
Content-Type: application/json

{
  "especie": "Agente Secreto",
  "raza": "Perry"

}

### Eliminar un tipo
DELETE http://localhost:3000/api/tipos/Cariñosito
