

### Devolver todas las razas
GET http://localhost:3000/api/razas/

### Crear una raza
# @name createRaza
POST http://localhost:3000/api/razas/
Content-Type: application/json

{
  "nomRaza": "bebe",
  "idEspecie": 4
}


### ID
@idRaza = {{ createRaza.response.body.data.idRaza }}

### Devolver una raza
GET http://localhost:3000/api/razas/1

### Actualizar una raza
PUT http://localhost:3000/api/razas/{{idRaza}}
Content-Type: application/json

{
  "nomRaza": "Dalmata"
}

### Eliminar una raza
DELETE http://localhost:3000/api/razas/{{idRaza}}