### Obtener todos los especies

GET http://localhost:3000/api/especies/

### Crear un especie 
# @name createEspecie
POST http://localhost:3000/api/especies/
Content-Type: application/json

{
  "nomEspecie": "Gato"
}


### ID
@idEspecie =  {{ createEspecie.response.body.data.idEspecie }}

### Devolver una especie
GET http://localhost:3000/api/especies/1


### Actualizar un especie
PUT http://localhost:3000/api/especies/{{idEspecie}}   
Content-Type: application/json

{
  "nomEspecie": "Nutria",
  "razas": []

}

### Eliminar un especie
DELETE http://localhost:3000/api/especies/{{idEspecie}}

