### HTTP

GET http://localhost:3000/api/usuarios

### HTTP POST

POST http://localhost:3000/api/usuarios/
Content-Type: application/json

{
  "email": "Pilaraguirrezabala@gmail.com",
  "password": "Brownie123"
}